database:
  host: ''
  username: ''
  password: ''
  name: ''
  collection: ''
scoreboard:
  title: '%primary%Arrow %secondary%[Dev]'
combat:
  timer: 25
  pearl: 16
prefixes:
  questionmark:
    display: '\u003F'
    prefix: '\u003F'
  dollarsign:
    display: '\u0024'
    prefix: '\u0024'
  gg:
    display: 'GG'
    prefix: 'GG'
themes:
  default:
    primary: '&6&l'
    secondary: '&e'
    value: '&r'
  test:
    primary: '&2&l'
    secondary: '&a'
    value: '&r'
  test2:
    primary: '&9&l'
    secondary: '&b'
    value: '&r'
worths:
  super:
    ratio: 10.00
    max: 50
    min: 41
  high:
    ratio: 8.00
    max: 40
    min: 31
  middle:
    max: 30
    min: 21
    ratio: 6.00
  low:
    max: 20
    min: 11
    ratio: 4.00
  default:
    max: 10
    min: 1
    ratio: 2.00